# .bashrc
# vim: set filetype=sh :

# source local aliases file
if [ -f ${HOME}/.bash_aliases ]
then
    . ${HOME}/.bash_aliases
fi

# source global bash script
if [ -f /etc/bashrc ]
then
    . /etc/bashrc
fi

# source local bash scripts
if [ -d ${HOME}/.local/bashrc.d ]
then
    for i in ${HOME}/.local/bashrc.d/*.sh
    do
        if [ -r $i ]
        then
            . $i
        fi
    done
    unset i
fi

set -o vi
